@extends('Adminpanel.layout.mainlayout')

@section('content')
<div class="container"><div class="page-inner">
    <div class="d-flex flex-column flex-md-row align-items-md-center pt-2 pb-4 gap-3"><div><h3 class="fw-bold mb-3">Financial Year History</h3>@include('Adminpanel.layout.breadcrumb', ['breadcrumbs' => [['label' => 'Dashboard', 'url' => route('hrms.dashboard')], ['label' => 'HRMS'], ['label' => 'Financial Year', 'url' => route('hrms.financial-year.index')], ['label' => 'History']]])</div><div class="ms-md-auto d-flex gap-2 d-print-none"><button class="btn btn-label-info" disabled>Export Excel</button><button class="btn btn-label-danger" disabled>Export PDF</button><button class="btn btn-light" onclick="window.print()">Print</button></div></div>
    <div class="card card-round mb-3 d-print-none"><div class="card-body"><form class="row g-3 align-items-end" method="GET"><div class="col-md-3"><label class="form-label">Financial Year</label><input class="form-control" name="financial_year" value="{{ $filters['financial_year'] ?? '' }}"></div><div class="col-md-3"><label class="form-label">Status</label><select name="status" class="form-select"><option value="">All</option>@foreach($statusOptions as $value => $label)<option value="{{ $value }}" @selected(($filters['status'] ?? '') === $value)>{{ $label }}</option>@endforeach</select></div><div class="col-md-2"><label class="form-label">Rows</label><select class="form-select" name="per_page">@foreach($perPageOptions as $option)<option value="{{ $option }}" @selected((int)($filters['per_page'] ?? 25) === $option)>{{ $option }}</option>@endforeach</select></div><div class="col-md-4 d-flex gap-2"><button class="btn btn-primary">Search</button><a href="{{ route('hrms.financial-year.history') }}" class="btn btn-light">Reset</a></div></form></div></div>
    <div class="card card-round"><div class="card-header"><div class="card-title">History</div></div><div class="card-body">@include('Adminpanel.HRMS.FinancialYear._partials.history-table')</div></div>
</div></div>
@endsection
