@extends('Adminpanel.layout.mainlayout')

@section('content')
@php($cards = [
    ['label' => 'Financial Year', 'value' => $closing->financial_year], ['label' => 'Status', 'value' => ucfirst($closing->status)], ['label' => 'Carry Forward', 'value' => $carry_forward], ['label' => 'Reset Summary', 'value' => $reset_summary], ['label' => 'Employee Count', 'value' => $employee_count], ['label' => 'Execution Time', 'value' => $closing->execution_time_ms . ' ms'],
])
<div class="container"><div class="page-inner">
    <div class="d-flex flex-column flex-md-row align-items-md-center pt-2 pb-4 gap-3"><div><h3 class="fw-bold mb-3">Financial Year Detail</h3>@include('Adminpanel.layout.breadcrumb', ['breadcrumbs' => [['label' => 'Dashboard', 'url' => route('hrms.dashboard')], ['label' => 'HRMS'], ['label' => 'Financial Year', 'url' => route('hrms.financial-year.index')], ['label' => $closing->financial_year]]])</div><div class="ms-md-auto d-flex gap-2 d-print-none"><button class="btn btn-label-info" disabled>Export Excel</button><button class="btn btn-label-danger" disabled>Export PDF</button><button class="btn btn-light" onclick="window.print()">Print</button>@if($closing->status === 'closed')<button class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#reopenFyModal">Reopen</button>@endif</div></div>
    @include('Adminpanel.HRMS.FinancialYear._partials.summary-cards')
    <div class="row"><div class="col-lg-6 mb-3"><div class="card card-round h-100"><div class="card-header"><div class="card-title">Execution Log</div></div><div class="card-body">@forelse($execution_log as $item)<div class="border-bottom py-2"><strong>{{ $item['employee'] ?? '-' }}</strong><div class="text-muted">{{ $item['message'] ?? '-' }}</div></div>@empty<div class="text-muted">No Report Data Found</div>@endforelse</div></div></div><div class="col-lg-6 mb-3"><div class="card card-round h-100"><div class="card-header"><div class="card-title">Audit Timeline</div></div><div class="card-body">@forelse($audit_timeline as $item)<div class="border-bottom py-2"><strong>{{ $item['action'] ?? '-' }}</strong><div class="text-muted">{{ $item['by'] ?? '-' }} · {{ $item['at'] ?? '-' }}</div></div>@empty<div class="text-muted">No Report Data Found</div>@endforelse</div></div></div></div>
    <div class="card card-round"><div class="card-header"><div class="card-title">Archive</div></div><div class="card-body table-responsive"><table class="table table-hover"><thead><tr><th>Employee</th><th>Department</th><th>Leave Type</th><th>Opening Balance</th><th>Consumed</th><th>Remaining</th><th>Carry Forward</th><th>Closing Balance</th></tr></thead><tbody>@forelse($archives as $archive)<tr><td>{{ $archive['employee'] }}</td><td>{{ $archive['department'] }}</td><td>{{ $archive['leave_type'] }}</td><td>{{ $archive['opening_balance'] }}</td><td>{{ $archive['consumed'] }}</td><td>{{ $archive['remaining'] }}</td><td>{{ $archive['carry_forward'] }}</td><td>{{ $archive['closing_balance'] }}</td></tr>@empty<tr><td colspan="8" class="text-center text-muted py-4">No Report Data Found</td></tr>@endforelse</tbody></table></div></div>
    @component('Adminpanel.HRMS.FinancialYear._partials.confirmation-modal', ['modalId' => 'reopenFyModal', 'title' => 'Reopen Financial Year', 'message' => 'Reopening Financial Year may affect leave balances. Continue?'])
        <form method="POST" action="{{ route('hrms.financial-year.reopen', $closing->id) }}">@csrf<button class="btn btn-warning">Reopen Financial Year</button></form>
    @endcomponent
</div></div>
@endsection
